"""Create Library Tables

Revision ID: fc5da1681166
Revises: fe56fa70289e
Create Date: 2026-01-23 21:39:02.411687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc5da1681166'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('book',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('isbn')
    )
    op.create_table('borrower',
    sa.Column('ssn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('bname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('book_authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], ),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.PrimaryKeyConstraint('author_id', 'isbn')
    )
    op.create_table('book_loans',
    sa.Column('date_out', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('due_date', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_in', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['borrower.card_id'], ),
    sa.ForeignKeyConstraint(['isbn'], ['book.isbn'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('fines',
    sa.Column('fine_amt', sa.Float(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['book_loans.loan_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fines')
    op.drop_table('book_loans')
    op.drop_table('book_authors')
    op.drop_table('borrower')
    op.drop_table('book')
    op.drop_table('authors')
    # ### end Alembic commands ###
